runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /(.*)
    static_files: dist/bq-visualizer/index.html
    upload: dist/bq-visualizer/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE