runtime: python27
api_version: 1
threadsafe: true

skip_files:
  - ^(?!dist) # Skip any files not in the dist folder

handlers:
  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico

  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/\1
    upload: dist/.*

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/.*
